kind: Deployment
apiVersion: apps/v1
metadata:
  name: andreas-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: andreas-website
  template:
    metadata:
      labels:
        app: andreas-website
    spec:
      containers:
        - name: andreas-website
          image: andreassujono/website
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: andreas-website
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: andreas-website