version: "3.8"

services: 
  frontend:
    image: node:13.12.0-alpine
    container_name: personal-website-frontend
    working_dir: /app
    command: sh -c "npm install && npm run start"
    ports:
      - 3001:3000
    volumes: 
      - ..:/app
    tty: true
